// words.js — word bank with categories and hints

const wordBank = [
  // Animals
  { word: "Dog", category: "Animals", hint: "A common household pet known for loyalty and barking" },
  { word: "Cat", category: "Animals", hint: "A popular pet that purrs and chases mice" },
  { word: "Horse", category: "Animals", hint: "A large animal people ride and use on farms" },
  { word: "Cow", category: "Animals", hint: "A farm animal that produces milk" },
  { word: "Pig", category: "Animals", hint: "A pink farm animal known for rolling in mud" },
  { word: "Chicken", category: "Animals", hint: "A common farm bird raised for eggs and meat" },
  { word: "Rabbit", category: "Animals", hint: "A fluffy animal with long ears that hops" },
  { word: "Duck", category: "Animals", hint: "A bird that quacks and swims on ponds" },
  { word: "Sheep", category: "Animals", hint: "A woolly farm animal that baas" },
  { word: "Goat", category: "Animals", hint: "A horned farm animal known for eating almost anything" },
  { word: "Lion", category: "Animals", hint: "A large wild cat known as the king of the jungle" },
  { word: "Tiger", category: "Animals", hint: "A large striped wild cat" },
  { word: "Bear", category: "Animals", hint: "A large furry animal that hibernates in winter" },
  { word: "Wolf", category: "Animals", hint: "A wild dog that howls and lives in packs" },
  { word: "Fox", category: "Animals", hint: "A small cunning wild animal with a bushy tail" },
  { word: "Deer", category: "Animals", hint: "A graceful animal with antlers found in forests" },
  { word: "Monkey", category: "Animals", hint: "A primate that climbs trees and swings on branches" },
  { word: "Penguin", category: "Animals", hint: "A flightless bird that swims and lives in cold climates" },
  { word: "Elephant", category: "Animals", hint: "The largest land animal with a long trunk" },
  { word: "Dolphin", category: "Animals", hint: "A smart ocean mammal known for jumping and playing" },
  { word: "Shark", category: "Animals", hint: "A large predatory fish with sharp teeth" },
  { word: "Frog", category: "Animals", hint: "A small amphibian that jumps and croaks near ponds" },
  { word: "Snake", category: "Animals", hint: "A legless reptile that slithers on the ground" },
  { word: "Parrot", category: "Animals", hint: "A colourful bird that can mimic human speech" },

  // Food
  { word: "Pizza", category: "Food", hint: "A round baked dish with cheese and toppings on dough" },
  { word: "Burger", category: "Food", hint: "A beef patty served inside a bun with toppings" },
  { word: "Sandwich", category: "Food", hint: "Fillings placed between two slices of bread" },
  { word: "Pasta", category: "Food", hint: "An Italian dish made from noodles cooked in sauce" },
  { word: "Rice", category: "Food", hint: "A staple grain eaten with nearly every cuisine in the world" },
  { word: "Salad", category: "Food", hint: "A cold dish of mixed vegetables, often with dressing" },
  { word: "Soup", category: "Food", hint: "A hot liquid dish with vegetables or meat, eaten with a spoon" },
  { word: "Fries", category: "Food", hint: "Deep-fried strips of potato, often eaten with ketchup" },
  { word: "Hotdog", category: "Food", hint: "A sausage served in a long bun" },
  { word: "Pancakes", category: "Food", hint: "Flat round cakes cooked on a pan, often topped with syrup" },
  { word: "Omelette", category: "Food", hint: "Beaten eggs cooked flat in a pan, often with fillings" },
  { word: "Ice Cream", category: "Food", hint: "A frozen sweet dessert that comes in many flavours" },
  { word: "Cookie", category: "Food", hint: "A small sweet baked treat, often with chocolate chips" },
  { word: "Donut", category: "Food", hint: "A round fried dough ring covered in glaze or sugar" },
  { word: "Sushi", category: "Food", hint: "A Japanese dish with rice and fish or other toppings" },
  { word: "Taco", category: "Food", hint: "A folded tortilla stuffed with meat and toppings" },
  { word: "Bacon", category: "Food", hint: "Strips of cured pork cooked until crispy" },
  { word: "Steak", category: "Food", hint: "A thick slice of beef cooked on a grill or pan" },
  { word: "Popcorn", category: "Food", hint: "Puffed corn kernels eaten as a snack, often at the cinema" },
  { word: "Waffles", category: "Food", hint: "A grid-patterned batter cake topped with syrup or fruit" },

  // Objects
  { word: "Chair", category: "Objects", hint: "A piece of furniture with four legs used for sitting" },
  { word: "Lamp", category: "Objects", hint: "A device that provides light in a room" },
  { word: "Umbrella", category: "Objects", hint: "A collapsible canopy carried to stay dry in the rain" },
  { word: "Backpack", category: "Objects", hint: "A bag worn on your back used to carry things" },
  { word: "Mirror", category: "Objects", hint: "A reflective surface used to see yourself" },
  { word: "Scissors", category: "Objects", hint: "A tool with two blades used to cut paper or fabric" },
  { word: "Clock", category: "Objects", hint: "A device that shows and tracks the time" },
  { word: "Wallet", category: "Objects", hint: "A small folding case used to carry money and cards" },
  { word: "Pillow", category: "Objects", hint: "A soft cushion you rest your head on when sleeping" },
  { word: "Blanket", category: "Objects", hint: "A large piece of soft fabric used to stay warm" },
  { word: "Toothbrush", category: "Objects", hint: "A small brush used to clean your teeth" },
  { word: "Soap", category: "Objects", hint: "A cleansing product used with water to wash your hands or body" },
  { word: "Key", category: "Objects", hint: "A small metal object used to lock and unlock doors" },
  { word: "Fork", category: "Objects", hint: "A utensil with prongs used to pick up food" },
  { word: "Mug", category: "Objects", hint: "A large handled cup used for hot drinks" },
  { word: "Candle", category: "Objects", hint: "A wax stick with a wick that burns to give light" },
  { word: "Bucket", category: "Objects", hint: "A round open container with a handle used to carry water" },
  { word: "Remote Control", category: "Objects", hint: "A handheld device used to operate a TV from a distance" },
  { word: "Sunglasses", category: "Objects", hint: "Tinted glasses worn to protect eyes from bright sunlight" },
  { word: "Bicycle", category: "Objects", hint: "A two-wheeled vehicle powered by pedalling" },

  // Sports
  { word: "Basketball", category: "Sports", hint: "A team sport where players score by shooting a ball through a hoop" },
  { word: "Soccer", category: "Sports", hint: "A team sport where players kick a ball into the opposing goal" },
  { word: "Tennis", category: "Sports", hint: "A racket sport played on a court divided by a net" },
  { word: "Swimming", category: "Sports", hint: "A sport where athletes race through water using different strokes" },
  { word: "Boxing", category: "Sports", hint: "A combat sport where two opponents punch each other wearing gloves" },
  { word: "Volleyball", category: "Sports", hint: "A team sport where players hit a ball over a net" },
  { word: "Baseball", category: "Sports", hint: "A bat-and-ball sport where players run around bases to score" },
  { word: "Gymnastics", category: "Sports", hint: "A sport involving flips, balancing, and acrobatic routines" },
  { word: "Skiing", category: "Sports", hint: "A winter sport where athletes slide down snow-covered slopes on skis" },
  { word: "Cycling", category: "Sports", hint: "A sport involving racing on bicycles over various terrains" },
  { word: "Wrestling", category: "Sports", hint: "A combat sport where opponents try to pin each other to the ground" },
  { word: "Golf", category: "Sports", hint: "A sport where players hit a small ball into a series of holes" },
  { word: "Badminton", category: "Sports", hint: "A racket sport played with a feathered shuttlecock over a net" },
  { word: "Rowing", category: "Sports", hint: "A water sport where athletes propel a boat using oars" },
  { word: "Skateboarding", category: "Sports", hint: "A sport where riders perform tricks on a wheeled board" },

  // Activities
  { word: "Surfing", category: "Activities", hint: "Riding ocean waves while standing on a board" },
  { word: "Archery", category: "Activities", hint: "A sport involving shooting arrows at a target" },
  { word: "Skydiving", category: "Activities", hint: "Jumping from an aircraft and freefalling before deploying a chute" },
  { word: "Pottery", category: "Activities", hint: "Shaping wet clay into objects, often on a spinning wheel" },
  { word: "Rock Climbing", category: "Activities", hint: "Ascending natural or artificial rock faces using hands and feet" },
  { word: "Meditation", category: "Activities", hint: "A mental practice of focused attention and calm breathing" },
  { word: "Fencing", category: "Activities", hint: "A sport involving combat with slender swords" },
];

function getRandomWord() {
  return wordBank[Math.floor(Math.random() * wordBank.length)];
}

module.exports = { wordBank, getRandomWord };
